### ISSUE TITLE
Upload images on web

### ISSUE THREAD

**Issue by oscarnar** [PauloniaAQP/mi_libro_vecino#13]
**Describe the bug**
When use _image_picker_ package I couldn't load an image from computer so this part on register needs review.

**To Reproduce**
1. Go to register, on personal photo and library photo.
2. Click on 'subir foto' and select an image.
3. The image loaded has an invalid path (I believe).

**Expected behavior**
We need a valid path for the image loaded and then show it on UI.

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by juanleondev** [comment]
@oscarnar this issue was resolved in #16 ? If yes, you can close the issue.

**Comment by oscarnar** [comment]
It was fixed on [PR#16](https://github.com/PauloniaAQP/mi_libro_vecino/pull/16)
